name: Warehouse-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Lint with Ruff
        run: |
          ruff check

      - name: Format with Black
        run: |
          black --check .

  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run tests
        run: |
          pytest tests/

  Run-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run demo
        run: |
          python src/main.py